app:
  host: "0.0.0.0"
  port: 8888
  security:
    read_token: "123"
    write_token: "321"
  storage: "inmemory"
log:
  level: "info"
  type: "json"
image:
  ext: "jpeg"
  max_dimension: 2000
storage:
  filesystem:
    path: "./data"
    lock_lifetime: "5s"
